## U33
# Ports of E2 (FPGA in / PAICORE out)
set_property -dict {PACKAGE_PIN  G6 IOSTANDARD LVCMOS18} [get_ports {REQ[0]}]
set_property -dict {PACKAGE_PIN  H2 IOSTANDARD LVCMOS18} [get_ports {ACK[0]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports {PDATA[31]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS18} [get_ports {PDATA[30]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS18} [get_ports {PDATA[29]}]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS18} [get_ports {PDATA[28]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS18} [get_ports {PDATA[27]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS18} [get_ports {PDATA[26]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS18} [get_ports {PDATA[25]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS18} [get_ports {PDATA[24]}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS18} [get_ports {PDATA[23]}]
set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS18} [get_ports {PDATA[22]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS18} [get_ports {PDATA[21]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS18} [get_ports {PDATA[20]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS18} [get_ports {PDATA[19]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS18} [get_ports {PDATA[18]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS18} [get_ports {PDATA[17]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports {PDATA[16]}]
set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS18} [get_ports {PDATA[15]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS18} [get_ports {PDATA[14]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS18} [get_ports {PDATA[13]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS18} [get_ports {PDATA[12]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS18} [get_ports {PDATA[11]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS18} [get_ports {PDATA[10]}]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS18} [get_ports {PDATA[9]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS18} [get_ports {PDATA[8]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS18} [get_ports {PDATA[7]}]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS18} [get_ports {PDATA[6]}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS18} [get_ports {PDATA[5]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS18} [get_ports {PDATA[4]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS18} [get_ports {PDATA[3]}]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports {PDATA[2]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS18} [get_ports {PDATA[1]}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS18} [get_ports {PDATA[0]}]

# U33
# Ports of E6 (FPGA out / PAICORE in)
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS18} [get_ports {REQ[1]}]
set_property -dict {PACKAGE_PIN  G1 IOSTANDARD LVCMOS18} [get_ports {ACK[1]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS18} [get_ports {PDATA[63]}]
set_property -dict {PACKAGE_PIN  L2 IOSTANDARD LVCMOS18} [get_ports {PDATA[62]}]
set_property -dict {PACKAGE_PIN  F2 IOSTANDARD LVCMOS18} [get_ports {PDATA[61]}]
set_property -dict {PACKAGE_PIN  K1 IOSTANDARD LVCMOS18} [get_ports {PDATA[60]}]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS18} [get_ports {PDATA[59]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS18} [get_ports {PDATA[58]}]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS18} [get_ports {PDATA[57]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS18} [get_ports {PDATA[56]}]
set_property -dict {PACKAGE_PIN  J3 IOSTANDARD LVCMOS18} [get_ports {PDATA[55]}]
set_property -dict {PACKAGE_PIN  K2 IOSTANDARD LVCMOS18} [get_ports {PDATA[54]}]
set_property -dict {PACKAGE_PIN  L1 IOSTANDARD LVCMOS18} [get_ports {PDATA[53]}]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS18} [get_ports {PDATA[52]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS18} [get_ports {PDATA[51]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS18} [get_ports {PDATA[50]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS18} [get_ports {PDATA[49]}]
set_property -dict {PACKAGE_PIN  K3 IOSTANDARD LVCMOS18} [get_ports {PDATA[48]}]
set_property -dict {PACKAGE_PIN  G2 IOSTANDARD LVCMOS18} [get_ports {PDATA[47]}]
set_property -dict {PACKAGE_PIN  J1 IOSTANDARD LVCMOS18} [get_ports {PDATA[46]}]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS18} [get_ports {PDATA[45]}]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS18} [get_ports {PDATA[44]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS18} [get_ports {PDATA[43]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS18} [get_ports {PDATA[42]}]
set_property -dict {PACKAGE_PIN  J5 IOSTANDARD LVCMOS18} [get_ports {PDATA[41]}]
set_property -dict {PACKAGE_PIN  L3 IOSTANDARD LVCMOS18} [get_ports {PDATA[40]}]
set_property -dict {PACKAGE_PIN  J4 IOSTANDARD LVCMOS18} [get_ports {PDATA[39]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS18} [get_ports {PDATA[38]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS18} [get_ports {PDATA[37]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS18} [get_ports {PDATA[36]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS18} [get_ports {PDATA[35]}]
set_property -dict {PACKAGE_PIN  K5 IOSTANDARD LVCMOS18} [get_ports {PDATA[34]}]
set_property -dict {PACKAGE_PIN  J6 IOSTANDARD LVCMOS18} [get_ports {PDATA[33]}]
set_property -dict {PACKAGE_PIN  K6 IOSTANDARD LVCMOS18} [get_ports {PDATA[32]}]

# E control signals
set_property -dict { PACKAGE_PIN H1 IOSTANDARD LVCMOS18 } [get_ports E_DONE ];
set_property -dict { PACKAGE_PIN H6 IOSTANDARD LVCMOS18 } [get_ports E_BUSY ];
set_property -dict { PACKAGE_PIN H3 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[0] } ]; # E_CLC
set_property -dict { PACKAGE_PIN H4 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[1] } ]; # E_SYNC
set_property -dict { PACKAGE_PIN G5 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[2] } ]; # E_INT


# U34
# Ports of S2 (FPGA out / PAICORE in)
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS18} [get_ports {REQ[2]}]
set_property -dict {PACKAGE_PIN  D5 IOSTANDARD LVCMOS18} [get_ports {ACK[2]}]
set_property -dict {PACKAGE_PIN M12 IOSTANDARD LVCMOS18} [get_ports {PDATA[95]}]
set_property -dict {PACKAGE_PIN  C6 IOSTANDARD LVCMOS18} [get_ports {PDATA[94]}]
set_property -dict {PACKAGE_PIN  D8 IOSTANDARD LVCMOS18} [get_ports {PDATA[93]}]
set_property -dict {PACKAGE_PIN  B6 IOSTANDARD LVCMOS18} [get_ports {PDATA[92]}]
set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS18} [get_ports {PDATA[91]}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS18} [get_ports {PDATA[90]}]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS18} [get_ports {PDATA[89]}]
set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVCMOS18} [get_ports {PDATA[88]}]
set_property -dict {PACKAGE_PIN  B7 IOSTANDARD LVCMOS18} [get_ports {PDATA[87]}]
set_property -dict {PACKAGE_PIN  C7 IOSTANDARD LVCMOS18} [get_ports {PDATA[86]}]
set_property -dict {PACKAGE_PIN  A7 IOSTANDARD LVCMOS18} [get_ports {PDATA[85]}]
set_property -dict {PACKAGE_PIN  J8 IOSTANDARD LVCMOS18} [get_ports {PDATA[84]}]
set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS18} [get_ports {PDATA[83]}]
set_property -dict {PACKAGE_PIN  H8 IOSTANDARD LVCMOS18} [get_ports {PDATA[82]}]
set_property -dict {PACKAGE_PIN  H9 IOSTANDARD LVCMOS18} [get_ports {PDATA[81]}]
set_property -dict {PACKAGE_PIN  C8 IOSTANDARD LVCMOS18} [get_ports {PDATA[80]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS18} [get_ports {PDATA[79]}]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS18} [get_ports {PDATA[78]}]
set_property -dict {PACKAGE_PIN  G9 IOSTANDARD LVCMOS18} [get_ports {PDATA[77]}]
set_property -dict {PACKAGE_PIN  F8 IOSTANDARD LVCMOS18} [get_ports {PDATA[76]}]
set_property -dict {PACKAGE_PIN  F4 IOSTANDARD LVCMOS18} [get_ports {PDATA[75]}]
set_property -dict {PACKAGE_PIN  E8 IOSTANDARD LVCMOS18} [get_ports {PDATA[74]}]
set_property -dict {PACKAGE_PIN  C9 IOSTANDARD LVCMOS18} [get_ports {PDATA[73]}]
set_property -dict {PACKAGE_PIN  B9 IOSTANDARD LVCMOS18} [get_ports {PDATA[72]}]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS18} [get_ports {PDATA[71]}]
set_property -dict {PACKAGE_PIN  F9 IOSTANDARD LVCMOS18} [get_ports {PDATA[70]}]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVCMOS18} [get_ports {PDATA[69]}]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS18} [get_ports {PDATA[68]}]
set_property -dict {PACKAGE_PIN  D9 IOSTANDARD LVCMOS18} [get_ports {PDATA[67]}]
set_property -dict {PACKAGE_PIN  A8 IOSTANDARD LVCMOS18} [get_ports {PDATA[66]}]
set_property -dict {PACKAGE_PIN  A9 IOSTANDARD LVCMOS18} [get_ports {PDATA[65]}]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS18} [get_ports {PDATA[64]}]

# U34
# Ports of S6 (FPGA out / PAICORE in)
set_property -dict {PACKAGE_PIN L10 IOSTANDARD LVCMOS18} [get_ports {REQ[3]}]
set_property -dict {PACKAGE_PIN  D4 IOSTANDARD LVCMOS18} [get_ports {ACK[3]}]
set_property -dict {PACKAGE_PIN M10 IOSTANDARD LVCMOS18} [get_ports {PDATA[127]}]
set_property -dict {PACKAGE_PIN  D1 IOSTANDARD LVCMOS18} [get_ports {PDATA[126]}]
set_property -dict {PACKAGE_PIN  D6 IOSTANDARD LVCMOS18} [get_ports {PDATA[125]}]
set_property -dict {PACKAGE_PIN  E7 IOSTANDARD LVCMOS18} [get_ports {PDATA[124]}]
set_property -dict {PACKAGE_PIN  L7 IOSTANDARD LVCMOS18} [get_ports {PDATA[123]}]
set_property -dict {PACKAGE_PIN  L8 IOSTANDARD LVCMOS18} [get_ports {PDATA[122]}]
set_property -dict {PACKAGE_PIN  L9 IOSTANDARD LVCMOS18} [get_ports {PDATA[121]}]
set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS18} [get_ports {PDATA[120]}]
set_property -dict {PACKAGE_PIN  C1 IOSTANDARD LVCMOS18} [get_ports {PDATA[119]}]
set_property -dict {PACKAGE_PIN  C4 IOSTANDARD LVCMOS18} [get_ports {PDATA[118]}]
set_property -dict {PACKAGE_PIN  C2 IOSTANDARD LVCMOS18} [get_ports {PDATA[117]}]
set_property -dict {PACKAGE_PIN  K8 IOSTANDARD LVCMOS18} [get_ports {PDATA[116]}]
set_property -dict {PACKAGE_PIN K10 IOSTANDARD LVCMOS18} [get_ports {PDATA[115]}]
set_property -dict {PACKAGE_PIN K11 IOSTANDARD LVCMOS18} [get_ports {PDATA[114]}]
set_property -dict {PACKAGE_PIN  K7 IOSTANDARD LVCMOS18} [get_ports {PDATA[113]}]
set_property -dict {PACKAGE_PIN  C3 IOSTANDARD LVCMOS18} [get_ports {PDATA[112]}]
set_property -dict {PACKAGE_PIN  B1 IOSTANDARD LVCMOS18} [get_ports {PDATA[111]}]
set_property -dict {PACKAGE_PIN  A2 IOSTANDARD LVCMOS18} [get_ports {PDATA[110]}]
set_property -dict {PACKAGE_PIN  J9 IOSTANDARD LVCMOS18} [get_ports {PDATA[109]}]
set_property -dict {PACKAGE_PIN  H7 IOSTANDARD LVCMOS18} [get_ports {PDATA[108]}]
set_property -dict {PACKAGE_PIN  G7 IOSTANDARD LVCMOS18} [get_ports {PDATA[107]}]
set_property -dict {PACKAGE_PIN  F7 IOSTANDARD LVCMOS18} [get_ports {PDATA[106]}]
set_property -dict {PACKAGE_PIN  B4 IOSTANDARD LVCMOS18} [get_ports {PDATA[105]}]
set_property -dict {PACKAGE_PIN  A4 IOSTANDARD LVCMOS18} [get_ports {PDATA[104]}]
set_property -dict {PACKAGE_PIN  B5 IOSTANDARD LVCMOS18} [get_ports {PDATA[103]}]
set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVCMOS18} [get_ports {PDATA[102]}]
set_property -dict {PACKAGE_PIN K12 IOSTANDARD LVCMOS18} [get_ports {PDATA[101]}]
set_property -dict {PACKAGE_PIN  F3 IOSTANDARD LVCMOS18} [get_ports {PDATA[100]}]
set_property -dict {PACKAGE_PIN  E1 IOSTANDARD LVCMOS18} [get_ports {PDATA[99]}]
set_property -dict {PACKAGE_PIN  B2 IOSTANDARD LVCMOS18} [get_ports {PDATA[98]}]
set_property -dict {PACKAGE_PIN  A3 IOSTANDARD LVCMOS18} [get_ports {PDATA[97]}]
set_property -dict {PACKAGE_PIN  A5 IOSTANDARD LVCMOS18} [get_ports {PDATA[96]}]

# S control signals
set_property -dict { PACKAGE_PIN E6 IOSTANDARD LVCMOS18 } [get_ports S_DONE ];
set_property -dict { PACKAGE_PIN L4 IOSTANDARD LVCMOS18 } [get_ports S_BUSY ];
set_property -dict { PACKAGE_PIN E3 IOSTANDARD LVCMOS18 } [get_ports { S_CTRL[0] } ]; # CLC
set_property -dict { PACKAGE_PIN D3 IOSTANDARD LVCMOS18 } [get_ports { S_CTRL[1] } ]; # SYNC
set_property -dict { PACKAGE_PIN E2 IOSTANDARD LVCMOS18 } [get_ports { S_CTRL[2] } ]; # INT