# Ports of E2 (FPGA in / PAICORE out)
set_property -dict { PACKAGE_PIN AB27 IOSTANDARD LVCMOS18 } [get_ports {REQ[0]}]
set_property -dict { PACKAGE_PIN AC27 IOSTANDARD LVCMOS18 } [get_ports {ACK[0]}]
set_property -dict { PACKAGE_PIN AC28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[31]}]
set_property -dict { PACKAGE_PIN AD28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[30]}]
set_property -dict { PACKAGE_PIN Y28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[29]}]
set_property -dict { PACKAGE_PIN AA29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[28]}]
set_property -dict { PACKAGE_PIN AA27 IOSTANDARD LVCMOS18 } [get_ports {PDATA[27]}]
set_property -dict { PACKAGE_PIN AA28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[26]}]
set_property -dict { PACKAGE_PIN AD30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[25]}]
set_property -dict { PACKAGE_PIN AE30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[24]}]
set_property -dict { PACKAGE_PIN AE28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[23]}]
set_property -dict { PACKAGE_PIN AF28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[22]}]
set_property -dict { PACKAGE_PIN AF30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[21]}]
set_property -dict { PACKAGE_PIN AG30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[20]}]
set_property -dict { PACKAGE_PIN AH28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[19]}]
set_property -dict { PACKAGE_PIN AH29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[18]}]
set_property -dict { PACKAGE_PIN AJ28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[17]}]
set_property -dict { PACKAGE_PIN AJ29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[16]}]
set_property -dict { PACKAGE_PIN AJ30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[15]}]
set_property -dict { PACKAGE_PIN AK30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[14]}]
set_property -dict { PACKAGE_PIN AC29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[13]}]
set_property -dict { PACKAGE_PIN AD29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[12]}]
set_property -dict { PACKAGE_PIN AB30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[11]}]
set_property -dict { PACKAGE_PIN AB29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[10]}]
set_property -dict { PACKAGE_PIN AG24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[9]}]
set_property -dict { PACKAGE_PIN AG25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[8]}]
set_property -dict { PACKAGE_PIN AJ23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[7]}]
set_property -dict { PACKAGE_PIN AJ24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[6]}]
set_property -dict { PACKAGE_PIN AJ20 IOSTANDARD LVCMOS18 } [get_ports {PDATA[5]}]
set_property -dict { PACKAGE_PIN AK20 IOSTANDARD LVCMOS18 } [get_ports {PDATA[4]}]
set_property -dict { PACKAGE_PIN AJ21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[3]}]
set_property -dict { PACKAGE_PIN AK21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[2]}]
set_property -dict { PACKAGE_PIN AK22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[1]}]
set_property -dict { PACKAGE_PIN AK23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[0]}]

# U3
# Ports of E6 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN AD23 IOSTANDARD LVCMOS18 } [get_ports {REQ[1]}]
set_property -dict { PACKAGE_PIN AE23 IOSTANDARD LVCMOS18 } [get_ports {ACK[1]}]
set_property -dict { PACKAGE_PIN AE22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[63]}]
set_property -dict { PACKAGE_PIN AF22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[62]}]
set_property -dict { PACKAGE_PIN Y26  IOSTANDARD LVCMOS18 } [get_ports {PDATA[61]}]
set_property -dict { PACKAGE_PIN Y27  IOSTANDARD LVCMOS18 } [get_ports {PDATA[60]}]
set_property -dict { PACKAGE_PIN Y30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[59]}]
set_property -dict { PACKAGE_PIN AA30 IOSTANDARD LVCMOS18 } [get_ports {PDATA[58]}]
set_property -dict { PACKAGE_PIN AB25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[57]}]
set_property -dict { PACKAGE_PIN AB26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[56]}]
set_property -dict { PACKAGE_PIN AC26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[55]}]
set_property -dict { PACKAGE_PIN AD26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[54]}]
set_property -dict { PACKAGE_PIN AD25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[53]}]
set_property -dict { PACKAGE_PIN AE26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[52]}]
set_property -dict { PACKAGE_PIN AE25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[51]}]
set_property -dict { PACKAGE_PIN AF25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[50]}]
set_property -dict { PACKAGE_PIN AG26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[49]}]
set_property -dict { PACKAGE_PIN AG27 IOSTANDARD LVCMOS18 } [get_ports {PDATA[48]}]
set_property -dict { PACKAGE_PIN AH26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[47]}]
set_property -dict { PACKAGE_PIN AH27 IOSTANDARD LVCMOS18 } [get_ports {PDATA[46]}]
set_property -dict { PACKAGE_PIN AJ26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[45]}]
set_property -dict { PACKAGE_PIN AK26 IOSTANDARD LVCMOS18 } [get_ports {PDATA[44]}]
set_property -dict { PACKAGE_PIN AK27 IOSTANDARD LVCMOS18 } [get_ports {PDATA[43]}]
set_property -dict { PACKAGE_PIN AK28 IOSTANDARD LVCMOS18 } [get_ports {PDATA[42]}]
set_property -dict { PACKAGE_PIN AE27 IOSTANDARD LVCMOS18 } [get_ports {PDATA[41]}]
set_property -dict { PACKAGE_PIN AF27 IOSTANDARD LVCMOS18 } [get_ports {PDATA[40]}]
set_property -dict { PACKAGE_PIN AF29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[39]}]
set_property -dict { PACKAGE_PIN AG29 IOSTANDARD LVCMOS18 } [get_ports {PDATA[38]}]
set_property -dict { PACKAGE_PIN AH23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[37]}]
set_property -dict { PACKAGE_PIN AH24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[36]}]
set_property -dict { PACKAGE_PIN AJ25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[35]}]
set_property -dict { PACKAGE_PIN AK25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[34]}]
set_property -dict { PACKAGE_PIN AB21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[33]}]
set_property -dict { PACKAGE_PIN AB22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[32]}]


# E control signals
set_property -dict { PACKAGE_PIN AC12 IOSTANDARD LVCMOS18 } [get_ports E_DONE ];
set_property -dict { PACKAGE_PIN AB12 IOSTANDARD LVCMOS18 } [get_ports E_BUSY ];
set_property -dict { PACKAGE_PIN AB14 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[0] } ]; # E_CLC
set_property -dict { PACKAGE_PIN AB15 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[1] } ]; # E_SYNC
set_property -dict { PACKAGE_PIN AE18 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[2] } ]; # E_INT