set_property PACKAGE_PIN Y8 [get_ports {diff_clock_rtl_0_clk_p[0]}]
create_clock -name sys_clk -period 10 [get_ports {diff_clock_rtl_0_clk_p[0]}]

set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS18} [get_ports reset_rtl_0]
set_false_path -from [get_ports reset_rtl_0]
set_property PULLUP true [get_ports reset_rtl_0]

set_property -dict { PACKAGE_PIN AK20   IOSTANDARD LVCMOS18 } [get_ports { LED[0] }];
set_property -dict { PACKAGE_PIN AL20   IOSTANDARD LVCMOS18 } [get_ports { LED[1] }];
set_property -dict { PACKAGE_PIN AJ22   IOSTANDARD LVCMOS18 } [get_ports { LED[2] }];

# U3
# Ports of E2 (FPGA in / PAICORE out)
set_property -dict { PACKAGE_PIN AR38 IOSTANDARD LVCMOS18 } [get_ports E2_REQ]
set_property -dict { PACKAGE_PIN AP40 IOSTANDARD LVCMOS18 } [get_ports E2_ACK]
set_property -dict { PACKAGE_PIN AN40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[31]}]
set_property -dict { PACKAGE_PIN AM42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[30]}]
set_property -dict { PACKAGE_PIN AM39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[29]}]
set_property -dict { PACKAGE_PIN AN38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[28]}]
set_property -dict { PACKAGE_PIN AT39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[27]}]
set_property -dict { PACKAGE_PIN AT40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[26]}]
set_property -dict { PACKAGE_PIN AR42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[25]}]
set_property -dict { PACKAGE_PIN AR40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[24]}]
set_property -dict { PACKAGE_PIN AP38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[23]}]
set_property -dict { PACKAGE_PIN AM41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[22]}]
set_property -dict { PACKAGE_PIN AR37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[21]}]
set_property -dict { PACKAGE_PIN AU42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[20]}]
set_property -dict { PACKAGE_PIN AR39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[19]}]
set_property -dict { PACKAGE_PIN AT41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[18]}]
set_property -dict { PACKAGE_PIN AT42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[17]}]
set_property -dict { PACKAGE_PIN AP42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[16]}]
set_property -dict { PACKAGE_PIN AN41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[15]}]
set_property -dict { PACKAGE_PIN AN39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[14]}]
set_property -dict { PACKAGE_PIN AY40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[13]}]
set_property -dict { PACKAGE_PIN AV38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[12]}]
set_property -dict { PACKAGE_PIN AV40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[11]}]
set_property -dict { PACKAGE_PIN AV39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[10]}]
set_property -dict { PACKAGE_PIN AT37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[9]}]
set_property -dict { PACKAGE_PIN AU39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[8]}]
set_property -dict { PACKAGE_PIN AP41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[7]}]
set_property -dict { PACKAGE_PIN AU38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[6]}]
set_property -dict { PACKAGE_PIN AW40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[5]}]
set_property -dict { PACKAGE_PIN AW38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[4]}]
set_property -dict { PACKAGE_PIN AY39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[3]}]
set_property -dict { PACKAGE_PIN AY38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[2]}]
set_property -dict { PACKAGE_PIN AW37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[1]}]
set_property -dict { PACKAGE_PIN AY37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[0]}]

# U3
# Ports of E6 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN AU22 IOSTANDARD LVCMOS18 } [get_ports {OUT_REQ[0]}]
set_property -dict { PACKAGE_PIN AW21 IOSTANDARD LVCMOS18 } [get_ports {OUT_ACK[0]}]
set_property -dict { PACKAGE_PIN AV23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[31]}]
set_property -dict { PACKAGE_PIN AW23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[30]}]
set_property -dict { PACKAGE_PIN AU24 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[29]}]
set_property -dict { PACKAGE_PIN AY25 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[28]}]
set_property -dict { PACKAGE_PIN AT22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[27]}]
set_property -dict { PACKAGE_PIN AU21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[26]}]
set_property -dict { PACKAGE_PIN AR22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[25]}]
set_property -dict { PACKAGE_PIN AV21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[24]}]
set_property -dict { PACKAGE_PIN AU23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[23]}]
set_property -dict { PACKAGE_PIN AY23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[22]}]
set_property -dict { PACKAGE_PIN AV24 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[21]}]
set_property -dict { PACKAGE_PIN AR24 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[20]}]
set_property -dict { PACKAGE_PIN AP22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[19]}]
set_property -dict { PACKAGE_PIN AN23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[18]}]
set_property -dict { PACKAGE_PIN AN21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[17]}]
set_property -dict { PACKAGE_PIN AR23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[16]}]
set_property -dict { PACKAGE_PIN AW22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[15]}]
set_property -dict { PACKAGE_PIN AT24 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[14]}]
set_property -dict { PACKAGE_PIN AP23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[13]}]
set_property -dict { PACKAGE_PIN AP21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[12]}]
set_property -dict { PACKAGE_PIN AM21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[11]}]
set_property -dict { PACKAGE_PIN AL22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[10]}]
set_property -dict { PACKAGE_PIN AM24 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[9]}]
set_property -dict { PACKAGE_PIN AN24 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[8]}]
set_property -dict { PACKAGE_PIN AY22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[7]}]
set_property -dict { PACKAGE_PIN AM22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[6]}]
set_property -dict { PACKAGE_PIN AL21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[5]}]
set_property -dict { PACKAGE_PIN AM23 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[4]}]
set_property -dict { PACKAGE_PIN AK22 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[3]}]
set_property -dict { PACKAGE_PIN AJ20 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[2]}]
set_property -dict { PACKAGE_PIN AJ21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[1]}]
set_property -dict { PACKAGE_PIN AT21 IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[0]}]


# U2
# Ports of W2 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN J21  IOSTANDARD LVCMOS18 } [get_ports {OUT_REQ[1]}]
set_property -dict { PACKAGE_PIN G22  IOSTANDARD LVCMOS18 } [get_ports {OUT_ACK[1]}]
set_property -dict { PACKAGE_PIN F22  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[63]}]
set_property -dict { PACKAGE_PIN H21  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[62]}]
set_property -dict { PACKAGE_PIN G21  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[61]}]
set_property -dict { PACKAGE_PIN G28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[60]}]
set_property -dict { PACKAGE_PIN G23  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[59]}]
set_property -dict { PACKAGE_PIN E23  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[58]}]
set_property -dict { PACKAGE_PIN E24  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[57]}]
set_property -dict { PACKAGE_PIN F25  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[56]}]
set_property -dict { PACKAGE_PIN G24  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[55]}]
set_property -dict { PACKAGE_PIN E22  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[54]}]
set_property -dict { PACKAGE_PIN H28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[53]}]
set_property -dict { PACKAGE_PIN E25  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[52]}]
set_property -dict { PACKAGE_PIN G26  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[51]}]
set_property -dict { PACKAGE_PIN G27  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[50]}]
set_property -dict { PACKAGE_PIN F27  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[49]}]
set_property -dict { PACKAGE_PIN K22  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[48]}]
set_property -dict { PACKAGE_PIN J28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[47]}]
set_property -dict { PACKAGE_PIN J27  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[46]}]
set_property -dict { PACKAGE_PIN F26  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[45]}]
set_property -dict { PACKAGE_PIN E27  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[44]}]
set_property -dict { PACKAGE_PIN J23  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[43]}]
set_property -dict { PACKAGE_PIN K23  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[42]}]
set_property -dict { PACKAGE_PIN J22  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[41]}]
set_property -dict { PACKAGE_PIN K28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[40]}]
set_property -dict { PACKAGE_PIN K27  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[39]}]
set_property -dict { PACKAGE_PIN H23  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[38]}]
set_property -dict { PACKAGE_PIN K24  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[37]}]
set_property -dict { PACKAGE_PIN H25  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[36]}]
set_property -dict { PACKAGE_PIN J25  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[35]}]
set_property -dict { PACKAGE_PIN H24  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[34]}]
set_property -dict { PACKAGE_PIN J26  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[33]}]
set_property -dict { PACKAGE_PIN H26  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[32]}]


# U2
# Ports of W6 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN L32  IOSTANDARD LVCMOS18 } [get_ports {OUT_REQ[2]}]
set_property -dict { PACKAGE_PIN M32  IOSTANDARD LVCMOS18 } [get_ports {OUT_ACK[2]}]
set_property -dict { PACKAGE_PIN T30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[95]}]
set_property -dict { PACKAGE_PIN K32  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[94]}]
set_property -dict { PACKAGE_PIN J31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[93]}]
set_property -dict { PACKAGE_PIN T31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[92]}]
set_property -dict { PACKAGE_PIN U31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[91]}]
set_property -dict { PACKAGE_PIN T29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[90]}]
set_property -dict { PACKAGE_PIN V29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[89]}]
set_property -dict { PACKAGE_PIN U29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[88]}]
set_property -dict { PACKAGE_PIN W31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[87]}]
set_property -dict { PACKAGE_PIN W30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[86]}]
set_property -dict { PACKAGE_PIN K29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[85]}]
set_property -dict { PACKAGE_PIN V31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[84]}]
set_property -dict { PACKAGE_PIN V30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[83]}]
set_property -dict { PACKAGE_PIN Y30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[82]}]
set_property -dict { PACKAGE_PIN Y29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[81]}]
set_property -dict { PACKAGE_PIN J30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[80]}]
set_property -dict { PACKAGE_PIN L29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[79]}]
set_property -dict { PACKAGE_PIN K30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[78]}]
set_property -dict { PACKAGE_PIN L30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[77]}]
set_property -dict { PACKAGE_PIN M28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[76]}]
set_property -dict { PACKAGE_PIN M29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[75]}]
set_property -dict { PACKAGE_PIN L31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[74]}]
set_property -dict { PACKAGE_PIN N28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[73]}]
set_property -dict { PACKAGE_PIN P31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[72]}]
set_property -dict { PACKAGE_PIN R30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[71]}]
set_property -dict { PACKAGE_PIN M31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[70]}]
set_property -dict { PACKAGE_PIN N29  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[69]}]
set_property -dict { PACKAGE_PIN N31  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[68]}]
set_property -dict { PACKAGE_PIN N30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[67]}]
set_property -dict { PACKAGE_PIN P28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[66]}]
set_property -dict { PACKAGE_PIN P30  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[65]}]
set_property -dict { PACKAGE_PIN R28  IOSTANDARD LVCMOS18 } [get_ports {OUT_DAT[64]}]

# E control signals
set_property -dict { PACKAGE_PIN AV41 IOSTANDARD LVCMOS18 } [get_ports E_DONE ];
set_property -dict { PACKAGE_PIN AW41 IOSTANDARD LVCMOS18 } [get_ports E_BUSY ];
set_property -dict { PACKAGE_PIN AU41 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[0] } ]; # E_CLC
set_property -dict { PACKAGE_PIN AW42 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[1] } ]; # E_SYNC
set_property -dict { PACKAGE_PIN AY42 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[2] } ]; # E_INT

# W control signals
set_property -dict { PACKAGE_PIN E15  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[0] } ]; # W_CLC
set_property -dict { PACKAGE_PIN E13  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[1] } ]; # W_SYNC
set_property -dict { PACKAGE_PIN E14  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[2] } ]; # W_INT

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]