set_property PACKAGE_PIN Y8 [get_ports {diff_clock_rtl_0_clk_p[0]}]
create_clock -name sys_clk -period 10 [get_ports {diff_clock_rtl_0_clk_p[0]}]

set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS18} [get_ports reset_rtl_0]
set_false_path -from [get_ports reset_rtl_0]
set_property PULLUP true [get_ports reset_rtl_0]

set_property -dict { PACKAGE_PIN AK20   IOSTANDARD LVCMOS18 } [get_ports { LED[0] }];
set_property -dict { PACKAGE_PIN AL20   IOSTANDARD LVCMOS18 } [get_ports { LED[1] }];
set_property -dict { PACKAGE_PIN AJ22   IOSTANDARD LVCMOS18 } [get_ports { LED[2] }];

# U3
# Ports of E2 (FPGA in / PAICORE out)
set_property -dict { PACKAGE_PIN AR38 IOSTANDARD LVCMOS18 } [get_ports {REQ[0]}]
set_property -dict { PACKAGE_PIN AP40 IOSTANDARD LVCMOS18 } [get_ports {ACK[0]}]
set_property -dict { PACKAGE_PIN AN40 IOSTANDARD LVCMOS18 } [get_ports {PDATA[31]}]
set_property -dict { PACKAGE_PIN AM42 IOSTANDARD LVCMOS18 } [get_ports {PDATA[30]}]
set_property -dict { PACKAGE_PIN AM39 IOSTANDARD LVCMOS18 } [get_ports {PDATA[29]}]
set_property -dict { PACKAGE_PIN AN38 IOSTANDARD LVCMOS18 } [get_ports {PDATA[28]}]
set_property -dict { PACKAGE_PIN AT39 IOSTANDARD LVCMOS18 } [get_ports {PDATA[27]}]
set_property -dict { PACKAGE_PIN AT40 IOSTANDARD LVCMOS18 } [get_ports {PDATA[26]}]
set_property -dict { PACKAGE_PIN AR42 IOSTANDARD LVCMOS18 } [get_ports {PDATA[25]}]
set_property -dict { PACKAGE_PIN AR40 IOSTANDARD LVCMOS18 } [get_ports {PDATA[24]}]
set_property -dict { PACKAGE_PIN AP38 IOSTANDARD LVCMOS18 } [get_ports {PDATA[23]}]
set_property -dict { PACKAGE_PIN AM41 IOSTANDARD LVCMOS18 } [get_ports {PDATA[22]}]
set_property -dict { PACKAGE_PIN AR37 IOSTANDARD LVCMOS18 } [get_ports {PDATA[21]}]
set_property -dict { PACKAGE_PIN AU42 IOSTANDARD LVCMOS18 } [get_ports {PDATA[20]}]
set_property -dict { PACKAGE_PIN AR39 IOSTANDARD LVCMOS18 } [get_ports {PDATA[19]}]
set_property -dict { PACKAGE_PIN AT41 IOSTANDARD LVCMOS18 } [get_ports {PDATA[18]}]
set_property -dict { PACKAGE_PIN AT42 IOSTANDARD LVCMOS18 } [get_ports {PDATA[17]}]
set_property -dict { PACKAGE_PIN AP42 IOSTANDARD LVCMOS18 } [get_ports {PDATA[16]}]
set_property -dict { PACKAGE_PIN AN41 IOSTANDARD LVCMOS18 } [get_ports {PDATA[15]}]
set_property -dict { PACKAGE_PIN AN39 IOSTANDARD LVCMOS18 } [get_ports {PDATA[14]}]
set_property -dict { PACKAGE_PIN AY40 IOSTANDARD LVCMOS18 } [get_ports {PDATA[13]}]
set_property -dict { PACKAGE_PIN AV38 IOSTANDARD LVCMOS18 } [get_ports {PDATA[12]}]
set_property -dict { PACKAGE_PIN AV40 IOSTANDARD LVCMOS18 } [get_ports {PDATA[11]}]
set_property -dict { PACKAGE_PIN AV39 IOSTANDARD LVCMOS18 } [get_ports {PDATA[10]}]
set_property -dict { PACKAGE_PIN AT37 IOSTANDARD LVCMOS18 } [get_ports {PDATA[9]}]
set_property -dict { PACKAGE_PIN AU39 IOSTANDARD LVCMOS18 } [get_ports {PDATA[8]}]
set_property -dict { PACKAGE_PIN AP41 IOSTANDARD LVCMOS18 } [get_ports {PDATA[7]}]
set_property -dict { PACKAGE_PIN AU38 IOSTANDARD LVCMOS18 } [get_ports {PDATA[6]}]
set_property -dict { PACKAGE_PIN AW40 IOSTANDARD LVCMOS18 } [get_ports {PDATA[5]}]
set_property -dict { PACKAGE_PIN AW38 IOSTANDARD LVCMOS18 } [get_ports {PDATA[4]}]
set_property -dict { PACKAGE_PIN AY39 IOSTANDARD LVCMOS18 } [get_ports {PDATA[3]}]
set_property -dict { PACKAGE_PIN AY38 IOSTANDARD LVCMOS18 } [get_ports {PDATA[2]}]
set_property -dict { PACKAGE_PIN AW37 IOSTANDARD LVCMOS18 } [get_ports {PDATA[1]}]
set_property -dict { PACKAGE_PIN AY37 IOSTANDARD LVCMOS18 } [get_ports {PDATA[0]}]


# U3
# Ports of E6 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN AU22 IOSTANDARD LVCMOS18 } [get_ports {REQ[1]}]
set_property -dict { PACKAGE_PIN AW21 IOSTANDARD LVCMOS18 } [get_ports {ACK[1]}]
set_property -dict { PACKAGE_PIN AV23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[63]}]
set_property -dict { PACKAGE_PIN AW23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[62]}]
set_property -dict { PACKAGE_PIN AU24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[61]}]
set_property -dict { PACKAGE_PIN AY25 IOSTANDARD LVCMOS18 } [get_ports {PDATA[60]}]
set_property -dict { PACKAGE_PIN AT22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[59]}]
set_property -dict { PACKAGE_PIN AU21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[58]}]
set_property -dict { PACKAGE_PIN AR22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[57]}]
set_property -dict { PACKAGE_PIN AV21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[56]}]
set_property -dict { PACKAGE_PIN AU23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[55]}]
set_property -dict { PACKAGE_PIN AY23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[54]}]
set_property -dict { PACKAGE_PIN AV24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[53]}]
set_property -dict { PACKAGE_PIN AR24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[52]}]
set_property -dict { PACKAGE_PIN AP22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[51]}]
set_property -dict { PACKAGE_PIN AN23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[50]}]
set_property -dict { PACKAGE_PIN AN21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[49]}]
set_property -dict { PACKAGE_PIN AR23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[48]}]
set_property -dict { PACKAGE_PIN AW22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[47]}]
set_property -dict { PACKAGE_PIN AT24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[46]}]
set_property -dict { PACKAGE_PIN AP23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[45]}]
set_property -dict { PACKAGE_PIN AP21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[44]}]
set_property -dict { PACKAGE_PIN AM21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[43]}]
set_property -dict { PACKAGE_PIN AL22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[42]}]
set_property -dict { PACKAGE_PIN AM24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[41]}]
set_property -dict { PACKAGE_PIN AN24 IOSTANDARD LVCMOS18 } [get_ports {PDATA[40]}]
set_property -dict { PACKAGE_PIN AY22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[39]}]
set_property -dict { PACKAGE_PIN AM22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[38]}]
set_property -dict { PACKAGE_PIN AL21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[37]}]
set_property -dict { PACKAGE_PIN AM23 IOSTANDARD LVCMOS18 } [get_ports {PDATA[36]}]
set_property -dict { PACKAGE_PIN AK22 IOSTANDARD LVCMOS18 } [get_ports {PDATA[35]}]
set_property -dict { PACKAGE_PIN AJ20 IOSTANDARD LVCMOS18 } [get_ports {PDATA[34]}]
set_property -dict { PACKAGE_PIN AJ21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[33]}]
set_property -dict { PACKAGE_PIN AT21 IOSTANDARD LVCMOS18 } [get_ports {PDATA[32]}]

# U2
# Ports of W2 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN J21  IOSTANDARD LVCMOS18 } [get_ports {REQ[2]}]
set_property -dict { PACKAGE_PIN G22  IOSTANDARD LVCMOS18 } [get_ports {ACK[2]}]
set_property -dict { PACKAGE_PIN F22  IOSTANDARD LVCMOS18 } [get_ports {PDATA[95]}]
set_property -dict { PACKAGE_PIN H21  IOSTANDARD LVCMOS18 } [get_ports {PDATA[94]}]
set_property -dict { PACKAGE_PIN G21  IOSTANDARD LVCMOS18 } [get_ports {PDATA[93]}]
set_property -dict { PACKAGE_PIN G28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[92]}]
set_property -dict { PACKAGE_PIN G23  IOSTANDARD LVCMOS18 } [get_ports {PDATA[91]}]
set_property -dict { PACKAGE_PIN E23  IOSTANDARD LVCMOS18 } [get_ports {PDATA[90]}]
set_property -dict { PACKAGE_PIN E24  IOSTANDARD LVCMOS18 } [get_ports {PDATA[89]}]
set_property -dict { PACKAGE_PIN F25  IOSTANDARD LVCMOS18 } [get_ports {PDATA[88]}]
set_property -dict { PACKAGE_PIN G24  IOSTANDARD LVCMOS18 } [get_ports {PDATA[87]}]
set_property -dict { PACKAGE_PIN E22  IOSTANDARD LVCMOS18 } [get_ports {PDATA[86]}]
set_property -dict { PACKAGE_PIN H28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[85]}]
set_property -dict { PACKAGE_PIN E25  IOSTANDARD LVCMOS18 } [get_ports {PDATA[84]}]
set_property -dict { PACKAGE_PIN G26  IOSTANDARD LVCMOS18 } [get_ports {PDATA[83]}]
set_property -dict { PACKAGE_PIN G27  IOSTANDARD LVCMOS18 } [get_ports {PDATA[82]}]
set_property -dict { PACKAGE_PIN F27  IOSTANDARD LVCMOS18 } [get_ports {PDATA[81]}]
set_property -dict { PACKAGE_PIN K22  IOSTANDARD LVCMOS18 } [get_ports {PDATA[80]}]
set_property -dict { PACKAGE_PIN J28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[79]}]
set_property -dict { PACKAGE_PIN J27  IOSTANDARD LVCMOS18 } [get_ports {PDATA[78]}]
set_property -dict { PACKAGE_PIN F26  IOSTANDARD LVCMOS18 } [get_ports {PDATA[77]}]
set_property -dict { PACKAGE_PIN E27  IOSTANDARD LVCMOS18 } [get_ports {PDATA[76]}]
set_property -dict { PACKAGE_PIN J23  IOSTANDARD LVCMOS18 } [get_ports {PDATA[75]}]
set_property -dict { PACKAGE_PIN K23  IOSTANDARD LVCMOS18 } [get_ports {PDATA[74]}]
set_property -dict { PACKAGE_PIN J22  IOSTANDARD LVCMOS18 } [get_ports {PDATA[73]}]
set_property -dict { PACKAGE_PIN K28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[72]}]
set_property -dict { PACKAGE_PIN K27  IOSTANDARD LVCMOS18 } [get_ports {PDATA[71]}]
set_property -dict { PACKAGE_PIN H23  IOSTANDARD LVCMOS18 } [get_ports {PDATA[70]}]
set_property -dict { PACKAGE_PIN K24  IOSTANDARD LVCMOS18 } [get_ports {PDATA[69]}]
set_property -dict { PACKAGE_PIN H25  IOSTANDARD LVCMOS18 } [get_ports {PDATA[68]}]
set_property -dict { PACKAGE_PIN J25  IOSTANDARD LVCMOS18 } [get_ports {PDATA[67]}]
set_property -dict { PACKAGE_PIN H24  IOSTANDARD LVCMOS18 } [get_ports {PDATA[66]}]
set_property -dict { PACKAGE_PIN J26  IOSTANDARD LVCMOS18 } [get_ports {PDATA[65]}]
set_property -dict { PACKAGE_PIN H26  IOSTANDARD LVCMOS18 } [get_ports {PDATA[64]}]


# U2
# Ports of W6 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN L32  IOSTANDARD LVCMOS18 } [get_ports {REQ[3]}]
set_property -dict { PACKAGE_PIN M32  IOSTANDARD LVCMOS18 } [get_ports {ACK[3]}]
set_property -dict { PACKAGE_PIN T30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[127]}]
set_property -dict { PACKAGE_PIN K32  IOSTANDARD LVCMOS18 } [get_ports {PDATA[126]}]
set_property -dict { PACKAGE_PIN J31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[125]}]
set_property -dict { PACKAGE_PIN T31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[124]}]
set_property -dict { PACKAGE_PIN U31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[123]}]
set_property -dict { PACKAGE_PIN T29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[122]}]
set_property -dict { PACKAGE_PIN V29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[121]}]
set_property -dict { PACKAGE_PIN U29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[120]}]
set_property -dict { PACKAGE_PIN W31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[119]}]
set_property -dict { PACKAGE_PIN W30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[118]}]
set_property -dict { PACKAGE_PIN K29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[117]}]
set_property -dict { PACKAGE_PIN V31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[116]}]
set_property -dict { PACKAGE_PIN V30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[115]}]
set_property -dict { PACKAGE_PIN Y30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[114]}]
set_property -dict { PACKAGE_PIN Y29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[113]}]
set_property -dict { PACKAGE_PIN J30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[112]}]
set_property -dict { PACKAGE_PIN L29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[111]}]
set_property -dict { PACKAGE_PIN K30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[110]}]
set_property -dict { PACKAGE_PIN L30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[109]}]
set_property -dict { PACKAGE_PIN M28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[108]}]
set_property -dict { PACKAGE_PIN M29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[107]}]
set_property -dict { PACKAGE_PIN L31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[106]}]
set_property -dict { PACKAGE_PIN N28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[105]}]
set_property -dict { PACKAGE_PIN P31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[104]}]
set_property -dict { PACKAGE_PIN R30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[103]}]
set_property -dict { PACKAGE_PIN M31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[102]}]
set_property -dict { PACKAGE_PIN N29  IOSTANDARD LVCMOS18 } [get_ports {PDATA[101]}]
set_property -dict { PACKAGE_PIN N31  IOSTANDARD LVCMOS18 } [get_ports {PDATA[100]}]
set_property -dict { PACKAGE_PIN N30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[99]}]
set_property -dict { PACKAGE_PIN P28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[98]}]
set_property -dict { PACKAGE_PIN P30  IOSTANDARD LVCMOS18 } [get_ports {PDATA[97]}]
set_property -dict { PACKAGE_PIN R28  IOSTANDARD LVCMOS18 } [get_ports {PDATA[96]}]

# E control signals
set_property -dict { PACKAGE_PIN AV41 IOSTANDARD LVCMOS18 } [get_ports E_DONE ];
set_property -dict { PACKAGE_PIN AW41 IOSTANDARD LVCMOS18 } [get_ports E_BUSY ];
set_property -dict { PACKAGE_PIN AU41 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[0] } ]; # E_CLC
set_property -dict { PACKAGE_PIN AW42 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[1] } ]; # E_SYNC
set_property -dict { PACKAGE_PIN AY42 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[2] } ]; # E_INT

# W control signals
set_property -dict { PACKAGE_PIN E15  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[0] } ]; # W_CLC
set_property -dict { PACKAGE_PIN E13  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[1] } ]; # W_SYNC
set_property -dict { PACKAGE_PIN E14  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[2] } ]; # W_INT

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]