set_property PACKAGE_PIN Y8 [get_ports {diff_clock_rtl_0_clk_p[0]}]
create_clock -name sys_clk -period 10 [get_ports {diff_clock_rtl_0_clk_p[0]}]

set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS18} [get_ports reset_rtl_0]
set_false_path -from [get_ports reset_rtl_0]
set_property PULLUP true [get_ports reset_rtl_0]

set_property -dict { PACKAGE_PIN AK20   IOSTANDARD LVCMOS18 } [get_ports { LED[0] }];
set_property -dict { PACKAGE_PIN AL20   IOSTANDARD LVCMOS18 } [get_ports { LED[1] }];
set_property -dict { PACKAGE_PIN AJ22   IOSTANDARD LVCMOS18 } [get_ports { LED[2] }];

# U3
# Ports of E2 (FPGA in / PAICORE out)
# set_property -dict { PACKAGE_PIN AR38 IOSTANDARD LVCMOS18 } [get_ports E2_REQ]
# set_property -dict { PACKAGE_PIN AP40 IOSTANDARD LVCMOS18 } [get_ports E2_ACK]
# set_property -dict { PACKAGE_PIN AN40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[31]}]
# set_property -dict { PACKAGE_PIN AM42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[30]}]
# set_property -dict { PACKAGE_PIN AM39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[29]}]
# set_property -dict { PACKAGE_PIN AN38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[28]}]
# set_property -dict { PACKAGE_PIN AT39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[27]}]
# set_property -dict { PACKAGE_PIN AT40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[26]}]
# set_property -dict { PACKAGE_PIN AR42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[25]}]
# set_property -dict { PACKAGE_PIN AR40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[24]}]
# set_property -dict { PACKAGE_PIN AP38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[23]}]
# set_property -dict { PACKAGE_PIN AM41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[22]}]
# set_property -dict { PACKAGE_PIN AR37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[21]}]
# set_property -dict { PACKAGE_PIN AU42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[20]}]
# set_property -dict { PACKAGE_PIN AR39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[19]}]
# set_property -dict { PACKAGE_PIN AT41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[18]}]
# set_property -dict { PACKAGE_PIN AT42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[17]}]
# set_property -dict { PACKAGE_PIN AP42 IOSTANDARD LVCMOS18 } [get_ports {din_E2[16]}]
# set_property -dict { PACKAGE_PIN AN41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[15]}]
# set_property -dict { PACKAGE_PIN AN39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[14]}]
# set_property -dict { PACKAGE_PIN AY40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[13]}]
# set_property -dict { PACKAGE_PIN AV38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[12]}]
# set_property -dict { PACKAGE_PIN AV40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[11]}]
# set_property -dict { PACKAGE_PIN AV39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[10]}]
# set_property -dict { PACKAGE_PIN AT37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[9]}]
# set_property -dict { PACKAGE_PIN AU39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[8]}]
# set_property -dict { PACKAGE_PIN AP41 IOSTANDARD LVCMOS18 } [get_ports {din_E2[7]}]
# set_property -dict { PACKAGE_PIN AU38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[6]}]
# set_property -dict { PACKAGE_PIN AW40 IOSTANDARD LVCMOS18 } [get_ports {din_E2[5]}]
# set_property -dict { PACKAGE_PIN AW38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[4]}]
# set_property -dict { PACKAGE_PIN AY39 IOSTANDARD LVCMOS18 } [get_ports {din_E2[3]}]
# set_property -dict { PACKAGE_PIN AY38 IOSTANDARD LVCMOS18 } [get_ports {din_E2[2]}]
# set_property -dict { PACKAGE_PIN AW37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[1]}]
# set_property -dict { PACKAGE_PIN AY37 IOSTANDARD LVCMOS18 } [get_ports {din_E2[0]}]

# Ports of E2 (FPGA in / PAICORE out)
set_property -dict { PACKAGE_PIN AU22 IOSTANDARD LVCMOS18 } [get_ports E6_REQ]
set_property -dict { PACKAGE_PIN AW21 IOSTANDARD LVCMOS18 } [get_ports E6_ACK]
set_property -dict { PACKAGE_PIN AV23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[31]}]
set_property -dict { PACKAGE_PIN AW23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[30]}]
set_property -dict { PACKAGE_PIN AU24 IOSTANDARD LVCMOS18 } [get_ports {din_E6[29]}]
set_property -dict { PACKAGE_PIN AY25 IOSTANDARD LVCMOS18 } [get_ports {din_E6[28]}]
set_property -dict { PACKAGE_PIN AT22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[27]}]
set_property -dict { PACKAGE_PIN AU21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[26]}]
set_property -dict { PACKAGE_PIN AR22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[25]}]
set_property -dict { PACKAGE_PIN AV21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[24]}]
set_property -dict { PACKAGE_PIN AU23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[23]}]
set_property -dict { PACKAGE_PIN AY23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[22]}]
set_property -dict { PACKAGE_PIN AV24 IOSTANDARD LVCMOS18 } [get_ports {din_E6[21]}]
set_property -dict { PACKAGE_PIN AR24 IOSTANDARD LVCMOS18 } [get_ports {din_E6[20]}]
set_property -dict { PACKAGE_PIN AP22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[19]}]
set_property -dict { PACKAGE_PIN AN23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[18]}]
set_property -dict { PACKAGE_PIN AN21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[17]}]
set_property -dict { PACKAGE_PIN AR23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[16]}]
set_property -dict { PACKAGE_PIN AW22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[15]}]
set_property -dict { PACKAGE_PIN AT24 IOSTANDARD LVCMOS18 } [get_ports {din_E6[14]}]
set_property -dict { PACKAGE_PIN AP23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[13]}]
set_property -dict { PACKAGE_PIN AP21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[12]}]
set_property -dict { PACKAGE_PIN AM21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[11]}]
set_property -dict { PACKAGE_PIN AL22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[10]}]
set_property -dict { PACKAGE_PIN AM24 IOSTANDARD LVCMOS18 } [get_ports {din_E6[9]}]
set_property -dict { PACKAGE_PIN AN24 IOSTANDARD LVCMOS18 } [get_ports {din_E6[8]}]
set_property -dict { PACKAGE_PIN AY22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[7]}]
set_property -dict { PACKAGE_PIN AM22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[6]}]
set_property -dict { PACKAGE_PIN AL21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[5]}]
set_property -dict { PACKAGE_PIN AM23 IOSTANDARD LVCMOS18 } [get_ports {din_E6[4]}]
set_property -dict { PACKAGE_PIN AK22 IOSTANDARD LVCMOS18 } [get_ports {din_E6[3]}]
set_property -dict { PACKAGE_PIN AJ20 IOSTANDARD LVCMOS18 } [get_ports {din_E6[2]}]
set_property -dict { PACKAGE_PIN AJ21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[1]}]
set_property -dict { PACKAGE_PIN AT21 IOSTANDARD LVCMOS18 } [get_ports {din_E6[0]}]

# U2
# Ports of W2 (FPGA out / PAICORE in)
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS18} [get_ports W2_REQ]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS18} [get_ports W2_ACK]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS18} [get_ports {dout_W2[31]}]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS18} [get_ports {dout_W2[30]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS18} [get_ports {dout_W2[29]}]
set_property -dict {PACKAGE_PIN G28 IOSTANDARD LVCMOS18} [get_ports {dout_W2[28]}]
set_property -dict {PACKAGE_PIN G23 IOSTANDARD LVCMOS18} [get_ports {dout_W2[27]}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS18} [get_ports {dout_W2[26]}]
set_property -dict {PACKAGE_PIN E24 IOSTANDARD LVCMOS18} [get_ports {dout_W2[25]}]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS18} [get_ports {dout_W2[24]}]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS18} [get_ports {dout_W2[23]}]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS18} [get_ports {dout_W2[22]}]
set_property -dict {PACKAGE_PIN H28 IOSTANDARD LVCMOS18} [get_ports {dout_W2[21]}]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS18} [get_ports {dout_W2[20]}]
set_property -dict {PACKAGE_PIN G26 IOSTANDARD LVCMOS18} [get_ports {dout_W2[19]}]
set_property -dict {PACKAGE_PIN G27 IOSTANDARD LVCMOS18} [get_ports {dout_W2[18]}]
set_property -dict {PACKAGE_PIN F27 IOSTANDARD LVCMOS18} [get_ports {dout_W2[17]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS18} [get_ports {dout_W2[16]}]
set_property -dict {PACKAGE_PIN J28 IOSTANDARD LVCMOS18} [get_ports {dout_W2[15]}]
set_property -dict {PACKAGE_PIN J27 IOSTANDARD LVCMOS18} [get_ports {dout_W2[14]}]
set_property -dict {PACKAGE_PIN F26 IOSTANDARD LVCMOS18} [get_ports {dout_W2[13]}]
set_property -dict {PACKAGE_PIN E27 IOSTANDARD LVCMOS18} [get_ports {dout_W2[12]}]
set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS18} [get_ports {dout_W2[11]}]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS18} [get_ports {dout_W2[10]}]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS18} [get_ports {dout_W2[9]}]
set_property -dict {PACKAGE_PIN K28 IOSTANDARD LVCMOS18} [get_ports {dout_W2[8]}]
set_property -dict {PACKAGE_PIN K27 IOSTANDARD LVCMOS18} [get_ports {dout_W2[7]}]
set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS18} [get_ports {dout_W2[6]}]
set_property -dict {PACKAGE_PIN K24 IOSTANDARD LVCMOS18} [get_ports {dout_W2[5]}]
set_property -dict {PACKAGE_PIN H25 IOSTANDARD LVCMOS18} [get_ports {dout_W2[4]}]
set_property -dict {PACKAGE_PIN J25 IOSTANDARD LVCMOS18} [get_ports {dout_W2[3]}]
set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS18} [get_ports {dout_W2[2]}]
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS18} [get_ports {dout_W2[1]}]
set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS18} [get_ports {dout_W2[0]}]


# U2
# Ports of W6 (FPGA out / PAICORE in)
set_property -dict { PACKAGE_PIN L32  IOSTANDARD LVCMOS18 } [get_ports W6_REQ]
set_property -dict { PACKAGE_PIN M32  IOSTANDARD LVCMOS18 } [get_ports W6_ACK]
set_property -dict { PACKAGE_PIN T30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[31]}]
set_property -dict { PACKAGE_PIN K32  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[30]}]
set_property -dict { PACKAGE_PIN J31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[29]}]
set_property -dict { PACKAGE_PIN T31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[28]}]
set_property -dict { PACKAGE_PIN U31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[27]}]
set_property -dict { PACKAGE_PIN T29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[26]}]
set_property -dict { PACKAGE_PIN V29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[25]}]
set_property -dict { PACKAGE_PIN U29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[24]}]
set_property -dict { PACKAGE_PIN W31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[23]}]
set_property -dict { PACKAGE_PIN W30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[22]}]
set_property -dict { PACKAGE_PIN K29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[21]}]
set_property -dict { PACKAGE_PIN V31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[20]}]
set_property -dict { PACKAGE_PIN V30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[19]}]
set_property -dict { PACKAGE_PIN Y30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[18]}]
set_property -dict { PACKAGE_PIN Y29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[17]}]
set_property -dict { PACKAGE_PIN J30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[16]}]
set_property -dict { PACKAGE_PIN L29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[15]}]
set_property -dict { PACKAGE_PIN K30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[14]}]
set_property -dict { PACKAGE_PIN L30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[13]}]
set_property -dict { PACKAGE_PIN M28  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[12]}]
set_property -dict { PACKAGE_PIN M29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[11]}]
set_property -dict { PACKAGE_PIN L31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[10]}]
set_property -dict { PACKAGE_PIN N28  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[9]}]
set_property -dict { PACKAGE_PIN P31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[8]}]
set_property -dict { PACKAGE_PIN R30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[7]}]
set_property -dict { PACKAGE_PIN M31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[6]}]
set_property -dict { PACKAGE_PIN N29  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[5]}]
set_property -dict { PACKAGE_PIN N31  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[4]}]
set_property -dict { PACKAGE_PIN N30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[3]}]
set_property -dict { PACKAGE_PIN P28  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[2]}]
set_property -dict { PACKAGE_PIN P30  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[1]}]
set_property -dict { PACKAGE_PIN R28  IOSTANDARD LVCMOS18 } [get_ports {dout_W6[0]}]

# E control signals
set_property -dict { PACKAGE_PIN AV41 IOSTANDARD LVCMOS18 } [get_ports E_DONE ];
set_property -dict { PACKAGE_PIN AW41 IOSTANDARD LVCMOS18 } [get_ports E_BUSY ];
set_property -dict { PACKAGE_PIN AU41 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[0] } ]; # E_CLC
set_property -dict { PACKAGE_PIN AW42 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[1] } ]; # E_SYNC
set_property -dict { PACKAGE_PIN AY42 IOSTANDARD LVCMOS18 } [get_ports { E_CTRL[2] } ]; # E_INT

# W control signals
set_property -dict { PACKAGE_PIN E15  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[0] } ]; # W_CLC
set_property -dict { PACKAGE_PIN E13  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[1] } ]; # W_SYNC
set_property -dict { PACKAGE_PIN E14  IOSTANDARD LVCMOS18 } [get_ports { W_CTRL[2] } ]; # W_INT

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]